---

# Copyright (c) 2017 Kabolt
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

# OS support verification

- name: Check OS support
  fail:
    msg: "Unsupported OS for docker role. Currently supported : Debian 8 & Debian 9"
  when: ansible_os_family != "Debian" and ( ansible_distribution_major_version == "9" or ansible_distribution_major_version == "8" )

# Install docker

- include: install.yml
  tags: docker_install

# Install Docker Compose

- include: compose.yml
  tags: docker_compose
  when: docker_compose_install
