---

# Copyright (c) 2018 Hexanode
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Reload systemctl daemon
  systemd:
    daemon_reload: yes

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
