---

# Copyright (c) 2018 Kabolt
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)

- name: Reload systemctl daemon
  command: systemctl daemon-reload

- name: Restart Docker
  service:
    name: docker
    state: restarted
